src/Library.UI/ViewModels/BookViewModel.cs
using System;

namespace Library.UI
{
	public class BookViewModel
	{
		public Guid BookId { get; set; }

		public string ISBN { get; set; }

		public string BookName { get; set; }

		public string Description { get; set; }

		public DateTime DateIssued { get; set; }
	}
}

src/Library.UI/Controllers/BookController.cs
using Library.UI.DTOs;
using Library.UI.Utilities;
using Library.UI.ViewModels;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Library.UI.Controllers
{
	public class BookController : BaseController
	{
		public BookController()
		{
		}

		[HttpGet]
		public ActionResult List()
		{
			var data = ApiRequest.Get<List<BookViewModel>>($"{_apiGatewayUrl}/api/books");
			return View(data);
		}

		[HttpGet]
		public ActionResult Add()
		{
			return View();
		}

		[HttpGet]
		public ActionResult Edit(Guid id)
		{
			var data = ApiRequest.Get<EditBookDTO>($"{_apiGatewayUrl}/api/books/{id}");

			return View(data);
		}

		[HttpPost]
		public ActionResult Edit(Guid id, EditBookDTO dto)
		{
			var commandId = ApiRequest.Put<Guid>($"{_apiGatewayUrl}/api/books/{dto.BookId}", dto);

			if (commandId != Guid.Empty)
			{
				return RedirectToAction("List");
			}
			else
			{
				return View(dto);
			}
		}

		[HttpPost]
		public ActionResult Add(AddBookDTO dto)
		{
			var commandUnqiueId = ApiRequest.Post<Guid>($"{_apiGatewayUrl}/api/books", dto);

			return Json(new { commandUnqiueId = commandUnqiueId });
		}

		[HttpGet]
		public ActionResult _AjaxGetAvailableBooks()
		{
			var data = ApiRequest.Get<List<AvailableBookModel>>($"{_apiGatewayUrl}/api/available_books");
			return Json(data, JsonRequestBehavior.AllowGet);
		}
	}
}

src/Library.UI/Controllers/BookInventoryController.cs
using BookingLibrary.UI.DTOs;
using Library.UI.DTOs;
using Library.UI.Utilities;
using Library.UI.ViewModels;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Web.Mvc;

namespace Library.UI.Controllers
{
	public class BookInventoryController : BaseController
	{
		public BookInventoryController()
		{
		}

		[HttpPost]
		public ActionResult _AjaxBulkImported(BulkImportDTO dto)
		{
			List<Guid> newBookInventories = new List<Guid>();

			//hard code 10 repsitory id
			for (var i = 0; i < dto.Number; i++)
			{
				newBookInventories.Add(Guid.NewGuid());
			}

			var data = new NameValueCollection();
			data.Add("BookRepositoryIds", string.Join(",", newBookInventories.Select(p => p.ToString())));
			var commandKey = ApiRequest.Post<Guid>($"{_apiGatewayUrl}/api/books/{dto.BookId}/inventories", new ImportBookInventoryDTO
			{
				BookInventoryIds = newBookInventories
			});

			return Content(commandKey.ToString());
		}

		[HttpGet]
		public ActionResult Histories(Guid id)
		{
			var histories = ApiRequest.Get<List<BookInventoryHistoryViewModel>>($"{_apiGatewayUrl}/api/inventories/{id}/histories");
			return View(histories);
		}

		[HttpPut]
		public ActionResult InStore(InStoreBookInventoryDTO dto)
		{
			var commandKey = ApiRequest.Put<Guid>($"{_apiGatewayUrl}/api/inventories/{dto.BookInventoryId}/status", new
			{
				Status = 1,
				Notes = dto.Note,
				OccurredDate = dto.OccurredDate
			});

			return Content(commandKey.ToString());
		}

		[HttpPut]
		public ActionResult OutStore(OutStoreBookInventoryDTO dto)
		{
			var commandKey = ApiRequest.Put<Guid>($"{_apiGatewayUrl}/api/inventories/{dto.BookInventoryId}/status", new
			{
				Status = 2,
				Notes = dto.Note,
				OccurredDate = dto.OccurredDate
			});

			return Content(commandKey.ToString());
		}
	}
}

src/Library.UI/Views/Book/Add.cshtml
@model Library.UI.DTOs.AddBookDTO
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Book</h2>

<section>
    @using (Html.BeginForm("Add", "Book", null, FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            <label for="tenantName" class="col-md-2 control-label">Book Name</label>
            <div class="col-md-10">
                @Html.TextBoxFor(p => p.BookName, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label for="email" class="col-md-2 control-label">ISBN</label>
            <div class="col-md-10">
                @Html.TextBoxFor(p => p.ISBN, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label for="email" class="col-md-2 control-label">Date Issued</label>
            <div class="col-md-10">
                @Html.TextBoxFor(p => p.IssueDate, new { @class = "form-control", @readonly = "readonly" })
            </div>
        </div>
        <div class="form-group">
            <label for="email" class="col-md-2 control-label">Description</label>
            <div class="col-md-10">
                @Html.TextAreaFor(p => p.Description, new { @style = "max-width: 100%", @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <input type="button" class="btn btn-default" value="Save" id="btnSave" />
            <input type="button" class="btn btn-default" value="Return" onclick="window.location='@Url.Action("List", "Book")'" />
        </div>

    }
</section>

@section header{

}

@section scripts{
    <script type="text/javascript">
        var currentCommandUnqiueId = null;

        $(function () {
            $.connection.hub.url = "@(ConfigurationManager.AppSettings["signalRUrl"])/signalr";
            $.connection.hub.logging = true;
            var command = $.connection.commandHub;

            command.client.success = function (commandUniqueId) {

                if (commandUniqueId == currentCommandUnqiueId) {
                    hideMask();
                    alert('Create successfully.');
                    command.server.removeCommand(currentCommandUnqiueId);
                    window.location = '@Url.Action("List", "Book")';
                }
            };

            command.client.failure = function (commandUniqueId, errorCode, errorMessage) {
                if (commandUniqueId == currentCommandUnqiueId) {
                    alert(errorMessage);
                    hideMask();
                }
            };

            $.connection.hub.start().done(function () {
                console.log("Connected.");
            });

            $("#IssueDate").datepicker({ dateFormat: "yy-mm-dd" });

            $('#btnSave').click(function () {
                showMask();

                $.ajax({
                    url: '',
                    data: { BookName: $('#BookName').val(), ISBN: $('#ISBN').val(), IssueDate: $('#IssueDate').val(), Description: $('#Description').val() },
                    type: 'POST',
                    success: function (data) {

                        if (data && data.commandUnqiueId) {
                           currentCommandUnqiueId = data.commandUnqiueId;
                        }

                        //hideMask();
                    },
                    error: function () {
                        hideMask();
                    }
                });
            });
        });
    </script>
}

src/Library.UI/Views/Book/Edit.cshtml
@model Library.UI.DTOs.EditBookDTO
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Book</h2>

<section>
    @using (Html.BeginForm("Edit", "Book", null, FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <fieldset>
            <legend>Book Information</legend>
            @Html.HiddenFor(p => p.BookId)
            <div class="form-group">
                <label for="tenantName" class="col-md-2 control-label">Book Name</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(p => p.BookName, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label for="email" class="col-md-2 control-label">ISBN</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(p => p.ISBN, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label for="email" class="col-md-2 control-label">Date Issued</label>
                <div class="col-md-10">
                    @Html.TextBoxFor(p => p.DateIssued, "{0:yyyy-MM-dd}", new { @class = "form-control", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group">
                <label for="email" class="col-md-2 control-label">Description</label>
                <div class="col-md-10">
                    @Html.TextAreaFor(p => p.Description, new { @style = "max-width: 100%", @class = "form-control" })
                </div>
            </div>
        </fieldset>
        <fieldset>
            <legend>Book Inventories</legend>
            <div style="margin-bottom:10px">
                <button class="btn btn-success" type="button">+ Add</button>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Unique Id</th>
                        <th>Status</th>
                        <th>Last Note</th>
                        <th>Opeation</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.BookInventories.Count > 0)
                    {
                        foreach (var item in Model.BookInventories)
                        {
                            <tr>
                                <td>@item.BookInventoryId</td>
                                <td>@(item.Status == 1 ? "IN" : "OUT")</td>
                                <td>@item.LastNote</td>
                                <td>
                                    @if (item.Status == 1)
                                    {
                                        <input type="button" class="btn btn-success outStoreOperation" data-id="@item.BookInventoryId" value="OUT" /><text>&nbsp;</text>
                                    }
                                    else
                                    {
                                        <input type="button" class="btn btn-success inStoreOperation" data-id="@item.BookInventoryId" value="IN" /><text>&nbsp;</text>
                                    }
                                    <input type="button" class="btn btn-success" value="View Histories" onclick="window.location='@Url.Action("Histories", "BookInventory", new { id = item.BookInventoryId })'" />
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="4">
                                No record.
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </fieldset>
        <div class="form-group">
            @*<input type="submit" class="btn btn-default" value="Save" />*@
            <input type="button" class="btn btn-default" value="Return" onclick="window.location='@Url.Action("List", "Book")'" />
        </div>
    }
</section>

<div class="modal fade" id="inStoreInventoryModal" tabindex="-1" role="dialog" aria-labelledby="inStoreInventory" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="inStoreInventory">Book Inventory IN</h4>
            </div>
            <div class="modal-body">
                <form role="form">
                    <div class="form-group">
                        <label for="bookInventoryInDate">Date</label>
                        <input name="bookInventoryInDate" class="form-control" id="bookInventoryInDate" type="date" />
                    </div>
                    <div class="form-group">
                        <label for="bookInventoryInNote">Note</label>
                        <textarea id="bookInventoryInNote" class="form-control" style="width:100% !important;max-width:100%" name="bookInventoryInNote"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="inStore()">IN</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>

<div class="modal fade" id="outStoreInventoryModal" tabindex="-1" role="dialog" aria-labelledby="outStoreInventory" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="outStoreInventory">Book Inventory OUT</h4>
            </div>
            <div class="modal-body">
                <form role="form">
                    <div class="form-group">
                        <label for="bookInventoryOutDate">Date</label>
                        <input name="bookInventoryOutDate" class="form-control" id="bookInventoryOutDate" type="date" />
                    </div>
                    <div class="form-group">
                        <label for="bookInventoryOutNote">Note</label>
                        <textarea id="bookInventoryOutNote" class="form-control" style="width:100% !important;max-width:100%" name="bookInventoryOutNote"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="inStore()">Out</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>

@section scripts{
    <script type="text/javascript">
        var bookId = '@Model.BookId';
        var bookInventoryId = null;
        var commandType = '';
        var currentCommandUnqiueId = null;

        function inStore() {
            $.ajax({
                url: '@Url.Action("InStore", "BookInventory")',
                type: 'put',
                data: { bookId = bookId, bookInventoryId = bookInventoryId, notes = $('#bookInventoryInNote').val(), occurredDate = $('#bookInventoryInDate').val() },
                success: function (data) {
                    commandType = 'inStoreBook';
                    currentCommandUnqiueId = data;
                }
            });
        }

        function outStore() {
            $.ajax({
                url: '@Url.Action("InStore", "BookInventory")',
                type: 'put',
                data: { bookId = bookId, bookInventoryId = bookInventoryId, notes = $('#bookInventoryOutNote').val(), occurredDate = $('#bookInventoryInDate').val() },
                success: function (data) {
                    commandType = 'outStoreBook';
                    currentCommandUnqiueId = data;
                }
            });
        }

        $(function () {

             $.connection.hub.url = "@(ConfigurationManager.AppSettings["signalRUrl"])/signalr";
            $.connection.hub.logging = true;
            var command = $.connection.commandHub;

            command.client.success = function (commandUniqueId) {

                hideMask();
                if (commandUniqueId == currentCommandUnqiueId && commandType == 'inStoreBook') {
                    alert('IN successfully.');
                    command.server.removeCommand(currentCommandUnqiueId);
                    window.location.reload();
                }
                else if (commandUniqueId == currentCommandUnqiueId && commandType == 'outStoreBook') {
                    alert('OUT successfully.');
                    command.server.removeCommand(currentCommandUnqiueId);
                    window.location.reload();
                }
            };

            command.client.failure = function (commandUniqueId, errorCode, errorMessage) {
                if (commandUniqueId == currentCommandUnqiueId && commandType == 'inStoreBook') {
                    alert(errorMessage);
                    resetCommand();
                }
                else ifif(commandUniqueId == currentCommandUnqiueId && commandType == 'outStoreBook') {
                    alert(errorMessage);
                    resetCommand();
                }
            };

            $.connection.hub.start().done(function () {
                console.log("Connected.");
            });

            $("#DateIssued").datepicker({ dateFormat: "yy-mm-dd" });

            $(".outStoreOperation").click(function () {
                bookInventoryId = $(this).attr('data-id');
                $('#outStoreInventoryModal').modal('show');
            });

            $(".inStoreOperation").click(function () {
                bookInventoryId = $(this).attr('data-id');
                $('#inStoreInventoryModal').modal('show');
            });
        });
    </script>
}

src/Library.UI/Views/Book/List.cshtml
@model List<Library.UI.BookViewModel>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Book Repository</h2>
<div style="margin-bottom:10px">
    <button class="btn btn-success" type="button" onclick="window.location = '@Url.Action("Add","Book")';">+ Add</button>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <th></th>
            <th>Book Name</th>
            <th>ISBN</th>
            <th>Issued Date</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count > 0)
        {
            var index = 1;
            foreach (var item in Model)
            {
                <tr>
                    <td>@index</td>
                    <td>@item.BookName</td>
                    <td>@item.ISBN</td>
                    <td>@item.DateIssued.ToString("yyyy-MM-dd")</td>
                    <td><button type="button" class="btn btn-primary" onclick="window.location='@Url.Action("Edit","Book", new { id=item.BookId})'">Edit</button>&nbsp;@*<button type="button" class="btn btn-danger">Delete</button>&nbsp;*@<button type="button" class="btn btn-primary" onclick="bulkImported('@item.BookId')">Bulk Imported</button></td>
                </tr>
                index++;
            }
        }
        else
        {
            <tr>
                <td colspan="6">
                    No Record.
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{
    <script type="text/javascript">
        var currentCommandUnqiueId = null;

        $(function () {
            $.connection.hub.url = "@(ConfigurationManager.AppSettings["signalRUrl"])/signalr";
            $.connection.hub.logging = true;
            var command = $.connection.commandHub;

            command.client.success = function (commandUniqueId) {

                if (commandUniqueId == currentCommandUnqiueId) {
                    hideMask();
                    alert('Bulk imported successfully.');

                    command.server.removeCommand(currentCommandUnqiueId);
                    currentCommandUnqiueId = null;
                }
            };

            command.client.failure = function (commandUniqueId) {
                if (commandUniqueId == currentCommandUnqiueId) {
                    alert('Bulk imported failure.');
                }
            };

            $.connection.hub.start().done(function () {
                console.log("Connected.");
            });
        });

        function bulkImported(bookId) {
            showMask();

            $.ajax({
                url: '@Url.Action("_AjaxBulkImported", "BookInventory")',
                data: {bookId:bookId, number:10},
                type: 'POST',
                success: function (data) {
                    currentCommandUnqiueId = data;
                }
            });
        }
    </script>

}