src/Library.UI/Controllers/BookController.cs
using Library.UI.DTOs;
using Library.UI.Utilities;
using Library.UI.ViewModels;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Library.UI.Controllers
{
	public class BookController : BaseController
	{
		public BookController()
		{
		}

		[HttpGet]
		public ActionResult List()
		{
			var data = ApiRequest.Get<List<BookViewModel>>($"{_apiGatewayUrl}/api/books");
			return View(data);
		}

		[HttpGet]
		public ActionResult Add()
		{
			return View();
		}

		[HttpGet]
		public ActionResult Edit(Guid id)
		{
			var data = ApiRequest.Get<EditBookDTO>($"{_apiGatewayUrl}/api/books/{id}");

			return View(data);
		}

		[HttpPost]
		public ActionResult Edit(Guid id, EditBookDTO dto)
		{
			var commandId = ApiRequest.Put<Guid>($"{_apiGatewayUrl}/api/books/{dto.BookId}", dto);

			if (commandId != Guid.Empty)
			{
				return RedirectToAction("List");
			}
			else
			{
				return View(dto);
			}
		}

		[HttpPost]
		public ActionResult Add(AddBookDTO dto)
		{
			var commandUnqiueId = ApiRequest.Post<Guid>($"{_apiGatewayUrl}/api/books", dto);

			return Json(new { commandUnqiueId = commandUnqiueId });
		}

		[HttpGet]
		public ActionResult _AjaxGetAvailableBooks()
		{
			var data = ApiRequest.Get<List<AvailableBookModel>>($"{_apiGatewayUrl}/api/available_books");
			return Json(data, JsonRequestBehavior.AllowGet);
		}
	}
}

src/Library.UI/Controllers/LogsController.cs
using Library.UI.Controllers;
using Library.UI.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace BookingLibrary.UI.Controllers
{
	public class LogsController : BaseController
	{
		public ActionResult List()
		{
			var data = ApiRequest.Get<List<BookingLibrary.UI.Models.LogItemViewModel>>($"{_apiGatewayUrl}/api/commandLogs");
			return View(data);
		}

		public ActionResult _AjaxListItem(Guid commandUniqueId)
		{
			var data = ApiRequest.Get<List<BookingLibrary.UI.Models.LogItemViewModel>>($"{_apiGatewayUrl}/api/commandLogs/{commandUniqueId}/eventLogs");

			if (data.Count > 0)
			{
				data = data.OrderByDescending(p => p.CreatedOn).ToList();
			}

			return PartialView("_EventLogs", data);
		}
	}
}

src/Library.UI/Views/Shared/_EventLogs.cshtml
@model List<BookingLibrary.UI.Models.LogItemViewModel>
@using BookingLibrary.UI.Utilities
@{

}

<h3>Events</h3>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Date Occurred</th>
            <th>Event Name</th>
            <th>Log Type</th>
            <th>Message</th>
            <th>Data</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count > 0)
        {
            var index = 1;
            foreach (var item in Model.OrderBy(p => p.CreatedOn))
            {
                <tr>
                    <td>@item.CreatedOn.ToString("yyyy-MM-dd HH:mm:ss")</td>
                    <td>@item.EventName</td>
                    <td>@item.LogType.ToString()</td>
                    <td>@item.Message</td>
                    <td><pre class="json">@item.Data.ConvertJsonString()</pre></td>
                </tr>
                index++;
            }
        }
        else
        {
            <tr>
                <td colspan="5">
                    No Record.
                </td>
            </tr>
        }
    </tbody>
</table>

src/Library.UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@using System.Configuration
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.structure.min.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.theme.min.css" rel="stylesheet" />

    @RenderSection("header", required: false)

    <style type="text/css">
        .mask {
            position: absolute;
            top: 0px;
            filter: alpha(opacity=60);
            background-color: #777;
            z-index: 1002;
            left: 0px;
            opacity: 0.5;
            -moz-opacity: 0.5;
        }
    </style>
</head>
<body>
    <div id="mask" class="mask"></div>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Book Library App("+ConfigurationManager.AppSettings["InstanceName"]+")", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (ViewBag.CurrentUser!=null)
                    {
                    <li>@Html.ActionLink("Books", "List", "Book")</li>
                    <li>@Html.ActionLink("Rental", "UnreturnedBooks", "Rental")</li>
                    <li>@Html.ActionLink("Command Logs", "List", "Logs")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Book Library App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery-ui.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="@(ConfigurationManager.AppSettings["signalRUrl"])/Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="@(ConfigurationManager.AppSettings["signalRUrl"])/signalr/hubs"></script>
    <script type="text/javascript">
        function showMask() {
            $("#mask").css("height", $(document).height());
            $("#mask").css("width", $(document).width());
            $("#mask").show();
        }

        function hideMask() {

            $("#mask").hide();
        }
    </script>
</body>
</html>